
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package AnaJson;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int CADENA = 4;
  public static final int COMA = 7;
  public static final int NUMEROS = 6;
  public static final int COMENTLINEA = 3;
  public static final int EOF = 0;
  public static final int LLAVEC = 10;
  public static final int COMENT = 2;
  public static final int ID = 5;
  public static final int LLAVEA = 9;
  public static final int error = 1;
  public static final int NOMBRE = 11;
  public static final int DPUNTOS = 8;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "COMENT",
  "COMENTLINEA",
  "CADENA",
  "ID",
  "NUMEROS",
  "COMA",
  "DPUNTOS",
  "LLAVEA",
  "LLAVEC",
  "NOMBRE"
  };
}

