// DO NOT EDIT
// Generated by JFlex 1.9.1 http://jflex.de/
// source: src/Analizador/s_lexico.jflex

package Analizador; 
import java_cup.runtime.*;
import Errores.Excepcion;
import Tokens.token;
import java.util.ArrayList;

@SuppressWarnings("fallthrough")
public class Lexico implements java_cup.runtime.Scanner {

  /** This character denotes the end of file. */
  public static final int YYEOF = -1;

  /** Initial size of the lookahead buffer. */
  private static final int ZZ_BUFFERSIZE = 16384;

  // Lexical states.
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = {
     0, 0
  };

  /**
   * Top-level table for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_TOP = zzUnpackcmap_top();

  private static final String ZZ_CMAP_TOP_PACKED_0 =
    "\1\0\1\u0100\36\u0200\1\u0300\1\u0400\266\u0200\10\u0500\u1020\u0200";

  private static int [] zzUnpackcmap_top() {
    int [] result = new int[4352];
    int offset = 0;
    offset = zzUnpackcmap_top(ZZ_CMAP_TOP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_top(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Second-level tables for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_BLOCKS = zzUnpackcmap_blocks();

  private static final String ZZ_CMAP_BLOCKS_PACKED_0 =
    "\11\0\1\1\1\2\1\3\2\1\22\0\1\4\1\5"+
    "\1\6\1\0\1\7\1\0\1\10\1\11\1\12\1\13"+
    "\1\14\1\15\1\16\1\17\1\20\1\21\12\22\1\23"+
    "\1\24\1\25\1\26\1\27\2\0\1\30\1\31\1\32"+
    "\1\33\1\34\1\35\1\36\1\37\1\40\1\41\1\42"+
    "\1\43\1\44\1\45\1\46\1\47\1\50\1\51\1\52"+
    "\1\53\1\54\1\55\1\56\1\57\1\60\1\50\1\61"+
    "\1\0\1\62\1\0\1\63\1\0\1\30\1\31\1\32"+
    "\1\33\1\34\1\35\1\36\1\37\1\40\1\41\1\42"+
    "\1\43\1\44\1\45\1\46\1\47\1\50\1\51\1\52"+
    "\1\53\1\54\1\55\1\56\1\57\1\60\1\50\1\64"+
    "\1\65\1\66\7\0\1\3\252\0\2\67\115\0\1\70"+
    "\u01a8\0\2\3\u0100\0\1\71\325\0\u0100\3";

  private static int [] zzUnpackcmap_blocks() {
    int [] result = new int[1536];
    int offset = 0;
    offset = zzUnpackcmap_blocks(ZZ_CMAP_BLOCKS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_blocks(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /**
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\1\1\1\2\1\3\1\1\1\4\2\1\1\5"+
    "\1\6\1\7\1\10\1\11\1\12\1\13\1\14\1\15"+
    "\1\16\1\17\1\20\1\21\14\22\1\23\1\24\1\25"+
    "\1\1\1\26\2\1\1\27\1\0\1\30\4\0\1\31"+
    "\1\32\1\33\6\22\1\34\4\22\1\35\6\22\1\0"+
    "\3\22\1\36\1\35\3\0\1\37\1\0\1\40\1\14"+
    "\3\22\1\0\6\22\1\0\1\22\1\41\1\42\3\22"+
    "\1\0\2\22\1\0\2\22\1\0\1\22\1\0\1\42"+
    "\1\0\1\43\1\44\1\22\2\45\1\46\1\22\1\0"+
    "\2\22\1\47\2\50\1\22\1\0\2\22\1\0\1\22"+
    "\1\0\1\22\1\51\1\0\2\22\1\0\1\22\1\0"+
    "\2\52\1\22\1\0\2\22\1\0\2\53\2\22\1\0"+
    "\1\22\1\0\1\22\1\0\1\22\1\0\2\54\1\22"+
    "\1\0\1\22\1\55\1\0\1\22\2\56\2\57\2\60"+
    "\1\22\3\0\1\22\1\0\1\61\1\62\1\22\1\63"+
    "\1\64\1\63\1\64\2\65\4\0\1\66\6\0\1\67"+
    "\11\0\1\70\10\0\1\71\5\0\1\72\1\0\1\73";

  private static int [] zzUnpackAction() {
    int [] result = new int[223];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\72\0\72\0\164\0\256\0\72\0\350\0\u0122"+
    "\0\72\0\72\0\72\0\72\0\72\0\72\0\u015c\0\u0196"+
    "\0\72\0\72\0\u01d0\0\u020a\0\u0244\0\u027e\0\u02b8\0\u02f2"+
    "\0\u032c\0\u0366\0\u03a0\0\u03da\0\u0414\0\u044e\0\u0488\0\u04c2"+
    "\0\u04fc\0\72\0\72\0\72\0\u0536\0\72\0\u0570\0\u05aa"+
    "\0\72\0\u05e4\0\72\0\u061e\0\u0658\0\u0692\0\u06cc\0\72"+
    "\0\72\0\72\0\u0706\0\u0740\0\u077a\0\u07b4\0\u07ee\0\u0828"+
    "\0\u0862\0\u089c\0\u08d6\0\u0910\0\u094a\0\u027e\0\u0984\0\u09be"+
    "\0\u09f8\0\u0a32\0\u0a6c\0\u0aa6\0\u0ae0\0\u0b1a\0\u0b54\0\u0b8e"+
    "\0\72\0\72\0\u0bc8\0\u0c02\0\u0c3c\0\72\0\u0c76\0\u0692"+
    "\0\u06cc\0\u0cb0\0\u0cea\0\u0d24\0\u0d5e\0\u0d98\0\u0dd2\0\u0e0c"+
    "\0\u0e46\0\u0e80\0\u0eba\0\u0ef4\0\u0f2e\0\u027e\0\u027e\0\u0f68"+
    "\0\u0fa2\0\u0fdc\0\u1016\0\u1050\0\u108a\0\u10c4\0\u10fe\0\u1138"+
    "\0\u1172\0\u11ac\0\u11e6\0\72\0\u1220\0\u0658\0\u027e\0\u125a"+
    "\0\u027e\0\72\0\u027e\0\u1294\0\u12ce\0\u1308\0\u1342\0\u027e"+
    "\0\u137c\0\u13b6\0\u13f0\0\u142a\0\u1464\0\u149e\0\u14d8\0\u1512"+
    "\0\u154c\0\u1586\0\u027e\0\u15c0\0\u15fa\0\u1634\0\u166e\0\u16a8"+
    "\0\u16e2\0\u027e\0\72\0\u171c\0\u1756\0\u1790\0\u17ca\0\u1804"+
    "\0\u027e\0\72\0\u183e\0\u1878\0\u18b2\0\u18ec\0\u1926\0\u1960"+
    "\0\u199a\0\u19d4\0\u1a0e\0\u027e\0\72\0\u1a48\0\u1a82\0\u1abc"+
    "\0\u027e\0\u1af6\0\u1b30\0\u027e\0\72\0\u027e\0\72\0\u1b6a"+
    "\0\u1ba4\0\u1bde\0\u1c18\0\u1c52\0\u1c8c\0\u1cc6\0\u1d00\0\u027e"+
    "\0\72\0\u1d3a\0\u027e\0\u027e\0\72\0\72\0\u027e\0\72"+
    "\0\u1d74\0\u1dae\0\u1de8\0\u1e22\0\u027e\0\u1e5c\0\u1e96\0\u1ed0"+
    "\0\u1f0a\0\u1f44\0\u1f7e\0\72\0\u1fb8\0\u1ff2\0\u202c\0\u2066"+
    "\0\u20a0\0\u20da\0\u2114\0\u214e\0\u2188\0\72\0\u21c2\0\u21fc"+
    "\0\u2236\0\u2270\0\u22aa\0\u22e4\0\u231e\0\u2358\0\72\0\u2392"+
    "\0\u23cc\0\u2406\0\u2440\0\u247a\0\72\0\u24b4\0\72";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[223];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length() - 1;
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /**
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpacktrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\2\3\1\0\1\3\1\4\1\5\1\6\1\7"+
    "\1\10\1\11\1\12\1\13\1\14\1\15\1\16\1\2"+
    "\1\17\1\20\1\21\1\22\1\23\1\24\1\25\1\26"+
    "\1\27\1\30\1\31\1\32\1\33\2\26\1\34\4\26"+
    "\1\35\4\26\1\36\1\37\1\26\1\40\1\41\2\26"+
    "\1\42\1\43\1\2\1\44\1\45\1\46\1\47\1\50"+
    "\1\2\120\0\1\51\43\0\2\52\1\0\3\52\1\0"+
    "\63\52\10\0\1\53\61\0\2\54\1\0\6\54\1\0"+
    "\60\54\14\0\1\55\4\0\1\56\70\0\1\57\1\0"+
    "\1\20\75\0\1\60\71\0\1\61\71\0\1\62\65\0"+
    "\1\26\5\0\31\26\2\0\1\26\30\0\1\26\5\0"+
    "\16\26\1\63\2\26\1\64\7\26\2\0\1\26\30\0"+
    "\1\26\5\0\1\65\6\26\1\66\6\26\1\67\12\26"+
    "\2\0\1\26\30\0\1\26\5\0\4\26\1\70\11\26"+
    "\1\71\12\26\2\0\1\26\30\0\1\26\5\0\11\26"+
    "\1\72\1\26\1\73\15\26\2\0\1\26\30\0\1\26"+
    "\5\0\1\74\15\26\1\75\12\26\2\0\1\26\30\0"+
    "\1\26\5\0\5\26\1\76\7\26\1\77\13\26\2\0"+
    "\1\26\30\0\1\26\5\0\4\26\1\100\24\26\2\0"+
    "\1\26\30\0\1\26\5\0\23\26\1\101\2\26\1\102"+
    "\2\26\2\0\1\26\30\0\1\26\5\0\10\26\1\103"+
    "\10\26\1\104\7\26\2\0\1\26\3\0\1\105\24\0"+
    "\1\26\5\0\1\106\15\26\1\107\12\26\2\0\1\26"+
    "\30\0\1\26\5\0\7\26\1\110\21\26\2\0\1\26"+
    "\73\0\1\111\41\0\1\112\7\0\1\113\77\0\1\114"+
    "\2\0\1\115\13\0\2\52\1\0\3\52\1\116\63\52"+
    "\2\54\1\0\6\54\1\116\60\54\5\55\1\0\6\55"+
    "\1\117\12\55\1\0\42\55\2\120\1\0\67\120\22\0"+
    "\1\121\71\0\1\26\5\0\16\26\1\122\12\26\2\0"+
    "\1\26\30\0\1\26\5\0\4\26\1\123\24\26\2\0"+
    "\1\26\30\0\1\26\5\0\22\26\1\124\6\26\2\0"+
    "\1\26\4\0\1\125\23\0\1\26\5\0\1\126\30\26"+
    "\2\0\1\26\30\0\1\26\5\0\15\26\1\127\13\26"+
    "\2\0\1\26\30\0\1\26\5\0\5\26\1\130\23\26"+
    "\2\0\1\26\30\0\1\26\5\0\24\26\1\131\4\26"+
    "\2\0\1\26\30\0\1\26\5\0\4\26\1\132\24\26"+
    "\2\0\1\26\30\0\1\26\5\0\22\26\1\133\6\26"+
    "\2\0\1\26\4\0\1\134\23\0\1\26\5\0\13\26"+
    "\1\135\15\26\2\0\1\26\30\0\1\26\5\0\21\26"+
    "\1\136\7\26\2\0\1\26\30\0\1\26\5\0\23\26"+
    "\1\137\5\26\2\0\1\26\30\0\1\26\5\0\26\26"+
    "\1\140\2\26\2\0\1\26\30\0\1\26\5\0\21\26"+
    "\1\141\7\26\2\0\1\26\30\0\1\26\5\0\10\26"+
    "\1\142\20\26\2\0\1\26\3\0\1\143\24\0\1\26"+
    "\5\0\23\26\1\144\5\26\2\0\1\26\30\0\1\26"+
    "\5\0\24\26\1\145\4\26\2\0\1\26\61\0\1\146"+
    "\40\0\1\26\5\0\13\26\1\147\15\26\2\0\1\26"+
    "\30\0\1\26\5\0\10\26\1\150\20\26\2\0\1\26"+
    "\3\0\1\151\24\0\1\26\5\0\10\26\1\152\20\26"+
    "\2\0\1\26\3\0\1\153\55\0\1\154\67\0\1\155"+
    "\60\0\1\143\26\0\1\143\2\0\5\55\1\0\6\55"+
    "\1\117\4\55\1\156\5\55\1\0\42\55\22\0\1\26"+
    "\5\0\13\26\1\157\15\26\2\0\1\26\30\0\1\26"+
    "\5\0\1\160\30\26\2\0\1\26\30\0\1\26\5\0"+
    "\4\26\1\161\24\26\2\0\1\26\42\0\1\162\57\0"+
    "\1\26\5\0\21\26\1\163\7\26\2\0\1\26\30\0"+
    "\1\26\5\0\22\26\1\164\6\26\2\0\1\26\4\0"+
    "\1\165\23\0\1\26\5\0\1\166\30\26\2\0\1\26"+
    "\30\0\1\26\5\0\1\26\1\167\27\26\2\0\1\26"+
    "\30\0\1\26\5\0\27\26\1\170\1\26\2\0\1\26"+
    "\30\0\1\26\5\0\4\26\1\171\24\26\2\0\1\26"+
    "\42\0\1\172\57\0\1\26\5\0\22\26\1\173\6\26"+
    "\2\0\1\26\4\0\1\174\23\0\1\26\5\0\25\26"+
    "\1\175\3\26\2\0\1\26\30\0\1\26\5\0\10\26"+
    "\1\176\20\26\2\0\1\26\3\0\1\177\24\0\1\26"+
    "\5\0\23\26\1\200\5\26\2\0\1\26\61\0\1\201"+
    "\40\0\1\26\5\0\24\26\1\202\4\26\2\0\1\26"+
    "\30\0\1\26\5\0\4\26\1\203\24\26\2\0\1\26"+
    "\62\0\1\204\37\0\1\26\5\0\16\26\1\205\12\26"+
    "\2\0\1\26\30\0\1\26\5\0\3\26\1\206\25\26"+
    "\2\0\1\26\41\0\1\207\60\0\1\26\5\0\13\26"+
    "\1\210\15\26\2\0\1\26\51\0\1\211\66\0\1\177"+
    "\26\0\1\177\24\0\1\26\5\0\12\26\1\212\16\26"+
    "\2\0\1\26\5\0\1\213\22\0\1\26\5\0\16\26"+
    "\1\214\12\26\2\0\1\26\54\0\1\215\45\0\1\26"+
    "\5\0\24\26\1\216\4\26\2\0\1\26\30\0\1\26"+
    "\5\0\13\26\1\217\15\26\2\0\1\26\12\0\1\220"+
    "\15\0\1\26\5\0\31\26\2\0\1\26\12\0\1\220"+
    "\107\0\1\26\5\0\4\26\1\221\24\26\2\0\1\26"+
    "\42\0\1\222\57\0\1\26\5\0\1\223\30\26\2\0"+
    "\1\26\30\0\1\26\5\0\15\26\1\224\13\26\2\0"+
    "\1\26\53\0\1\225\46\0\1\26\5\0\2\26\1\226"+
    "\26\26\2\0\1\26\40\0\1\227\61\0\1\26\5\0"+
    "\13\26\1\230\15\26\2\0\1\26\51\0\1\231\50\0"+
    "\1\26\5\0\21\26\1\232\7\26\2\0\1\26\12\0"+
    "\1\233\15\0\1\26\5\0\31\26\2\0\1\26\12\0"+
    "\1\233\107\0\1\26\5\0\4\26\1\234\24\26\2\0"+
    "\1\26\42\0\1\235\57\0\1\26\5\0\13\26\1\236"+
    "\15\26\2\0\1\26\51\0\1\237\50\0\1\26\5\0"+
    "\13\26\1\240\15\26\2\0\1\26\30\0\1\26\5\0"+
    "\4\26\1\241\24\26\2\0\1\26\46\0\1\242\26\0"+
    "\1\242\24\0\1\26\5\0\13\26\1\243\15\26\2\0"+
    "\1\26\30\0\1\26\5\0\6\26\1\244\22\26\2\0"+
    "\1\26\44\0\1\245\55\0\1\26\5\0\7\26\1\246"+
    "\21\26\2\0\1\26\45\0\1\247\54\0\1\26\5\0"+
    "\16\26\1\250\12\26\2\0\1\26\54\0\1\251\45\0"+
    "\1\26\5\0\4\26\1\252\24\26\2\0\1\26\41\0"+
    "\1\253\2\0\1\254\5\0\1\255\47\0\1\26\5\0"+
    "\4\26\1\256\24\26\2\0\1\26\42\0\1\257\57\0"+
    "\1\26\5\0\23\26\1\260\5\26\2\0\1\26\43\0"+
    "\1\261\56\0\1\26\5\0\16\26\1\262\12\26\2\0"+
    "\1\26\30\0\1\26\5\0\27\26\1\263\1\264\2\0"+
    "\1\26\65\0\1\265\1\266\33\0\1\26\5\0\22\26"+
    "\1\267\6\26\2\0\1\26\4\0\1\270\35\0\1\271"+
    "\106\0\1\272\50\0\1\273\61\0\1\274\1\0\1\26"+
    "\5\0\31\26\2\0\1\26\26\0\1\274\73\0\1\26"+
    "\5\0\21\26\1\275\7\26\2\0\1\26\43\0\1\276"+
    "\64\0\1\277\101\0\1\300\26\0\1\300\60\0\1\301"+
    "\53\0\1\302\26\0\1\302\37\0\1\303\101\0\1\304"+
    "\75\0\1\305\65\0\1\306\64\0\1\307\26\0\1\307"+
    "\42\0\1\310\26\0\1\310\42\0\1\311\26\0\1\311"+
    "\34\0\1\312\112\0\1\313\67\0\1\314\50\0\1\315"+
    "\75\0\1\316\73\0\1\317\64\0\1\320\15\0\1\321"+
    "\65\0\1\322\56\0\1\323\101\0\1\324\26\0\1\324"+
    "\50\0\1\325\74\0\1\326\54\0\1\327\66\0\1\330"+
    "\111\0\1\331\50\0\1\332\71\0\1\333\104\0\1\334"+
    "\100\0\1\335\15\0\1\335\35\0\1\336\107\0\1\337"+
    "\15\0\1\337\1\0";

  private static int [] zzUnpacktrans() {
    int [] result = new int[9454];
    int offset = 0;
    offset = zzUnpacktrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpacktrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** Error code for "Unknown internal scanner error". */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  /** Error code for "could not match input". */
  private static final int ZZ_NO_MATCH = 1;
  /** Error code for "pushback value was too large". */
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /**
   * Error messages for {@link #ZZ_UNKNOWN_ERROR}, {@link #ZZ_NO_MATCH}, and
   * {@link #ZZ_PUSHBACK_2BIG} respectively.
   */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state {@code aState}
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\2\11\2\1\1\11\2\1\6\11\2\1\2\11"+
    "\17\1\3\11\1\1\1\11\2\1\1\11\1\0\1\11"+
    "\4\0\3\11\22\1\1\0\3\1\2\11\3\0\1\11"+
    "\1\0\5\1\1\0\6\1\1\0\6\1\1\0\2\1"+
    "\1\0\2\1\1\0\1\1\1\0\1\11\1\0\4\1"+
    "\1\11\2\1\1\0\6\1\1\0\2\1\1\0\1\1"+
    "\1\0\2\1\1\0\2\1\1\0\1\1\1\0\1\1"+
    "\1\11\1\1\1\0\2\1\1\0\1\1\1\11\2\1"+
    "\1\0\1\1\1\0\1\1\1\0\1\1\1\0\1\1"+
    "\1\11\1\1\1\0\2\1\1\0\2\1\1\11\1\1"+
    "\1\11\3\1\3\0\1\1\1\0\1\1\1\11\3\1"+
    "\2\11\1\1\1\11\4\0\1\1\6\0\1\11\11\0"+
    "\1\11\10\0\1\11\5\0\1\11\1\0\1\11";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[223];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** Input device. */
  private java.io.Reader zzReader;

  /** Current state of the DFA. */
  private int zzState;

  /** Current lexical state. */
  private int zzLexicalState = YYINITIAL;

  /**
   * This buffer contains the current text to be matched and is the source of the {@link #yytext()}
   * string.
   */
  private char zzBuffer[] = new char[Math.min(ZZ_BUFFERSIZE, zzMaxBufferLen())];

  /** Text position at the last accepting state. */
  private int zzMarkedPos;

  /** Current text position in the buffer. */
  private int zzCurrentPos;

  /** Marks the beginning of the {@link #yytext()} string in the buffer. */
  private int zzStartRead;

  /** Marks the last character in the buffer, that has been read from input. */
  private int zzEndRead;

  /**
   * Whether the scanner is at the end of file.
   * @see #yyatEOF
   */
  private boolean zzAtEOF;

  /**
   * The number of occupied positions in {@link #zzBuffer} beyond {@link #zzEndRead}.
   *
   * <p>When a lead/high surrogate has been read from the input stream into the final
   * {@link #zzBuffer} position, this will have a value of 1; otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /** Number of newlines encountered up to the start of the matched text. */
  private int yyline;

  /** Number of characters from the last newline up to the start of the matched text. */
  private int yycolumn;

  /** Number of characters up to the start of the matched text. */
  private long yychar;

  /** Whether the scanner is currently at the beginning of a line. */
  @SuppressWarnings("unused")
  private boolean zzAtBOL = true;

  /** Whether the user-EOF-code has already been executed. */
  private boolean zzEOFDone;

  /* user code: */

        // crear un arraylist para los errores lexicos
        public  ArrayList<Excepcion> erroresLexicos = new ArrayList<Excepcion>() ;
        // array tokens
        public  ArrayList<token> Rtokens = new ArrayList<token>() ;


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public Lexico(java.io.Reader in) {
    this.zzReader = in;
  }


  /** Returns the maximum size of the scanner buffer, which limits the size of tokens. */
  private int zzMaxBufferLen() {
    return Integer.MAX_VALUE;
  }

  /**  Whether the scanner buffer can grow to accommodate a larger token. */
  private boolean zzCanGrow() {
    return true;
  }

  /**
   * Translates raw input code points to DFA table row
   */
  private static int zzCMap(int input) {
    int offset = input & 255;
    return offset == input ? ZZ_CMAP_BLOCKS[offset] : ZZ_CMAP_BLOCKS[ZZ_CMAP_TOP[input >> 8] | offset];
  }

  /**
   * Refills the input buffer.
   *
   * @return {@code false} iff there was new input.
   * @exception java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead - zzStartRead);

      /* translate stored positions */
      zzEndRead -= zzStartRead;
      zzCurrentPos -= zzStartRead;
      zzMarkedPos -= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate && zzCanGrow()) {
      /* if not, and it can grow: blow it up */
      char newBuffer[] = new char[Math.min(zzBuffer.length * 2, zzMaxBufferLen())];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      if (requested == 0) {
        throw new java.io.EOFException("Scan buffer limit reached ["+zzBuffer.length+"]");
      }
      else {
        throw new java.io.IOException(
            "Reader returned 0 characters. See JFlex examples/zero-reader for a workaround.");
      }
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
        if (numRead == requested) { // We requested too few chars to encode a full Unicode character
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        } else {                    // There is room in the buffer for at least one more char
          int c = zzReader.read();  // Expecting to read a paired low surrogate char
          if (c == -1) {
            return true;
          } else {
            zzBuffer[zzEndRead++] = (char)c;
          }
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }


  /**
   * Closes the input reader.
   *
   * @throws java.io.IOException if the reader could not be closed.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true; // indicate end of file
    zzEndRead = zzStartRead; // invalidate buffer

    if (zzReader != null) {
      zzReader.close();
    }
  }


  /**
   * Resets the scanner to read from a new input stream.
   *
   * <p>Does not close the old reader.
   *
   * <p>All internal variables are reset, the old input stream <b>cannot</b> be reused (internal
   * buffer is discarded and lost). Lexical state is set to {@code ZZ_INITIAL}.
   *
   * <p>Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader The new input stream.
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzEOFDone = false;
    yyResetPosition();
    zzLexicalState = YYINITIAL;
    int initBufferSize = Math.min(ZZ_BUFFERSIZE, zzMaxBufferLen());
    if (zzBuffer.length > initBufferSize) {
      zzBuffer = new char[initBufferSize];
    }
  }

  /**
   * Resets the input position.
   */
  private final void yyResetPosition() {
      zzAtBOL  = true;
      zzAtEOF  = false;
      zzCurrentPos = 0;
      zzMarkedPos = 0;
      zzStartRead = 0;
      zzEndRead = 0;
      zzFinalHighSurrogate = 0;
      yyline = 0;
      yycolumn = 0;
      yychar = 0L;
  }


  /**
   * Returns whether the scanner has reached the end of the reader it reads from.
   *
   * @return whether the scanner has reached EOF.
   */
  public final boolean yyatEOF() {
    return zzAtEOF;
  }


  /**
   * Returns the current lexical state.
   *
   * @return the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state.
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   *
   * @return the matched text.
   */
  public final String yytext() {
    return new String(zzBuffer, zzStartRead, zzMarkedPos-zzStartRead);
  }


  /**
   * Returns the character at the given position from the matched text.
   *
   * <p>It is equivalent to {@code yytext().charAt(pos)}, but faster.
   *
   * @param position the position of the character to fetch. A value from 0 to {@code yylength()-1}.
   *
   * @return the character at {@code position}.
   */
  public final char yycharat(int position) {
    return zzBuffer[zzStartRead + position];
  }


  /**
   * How many characters were matched.
   *
   * @return the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occurred while scanning.
   *
   * <p>In a well-formed scanner (no or only correct usage of {@code yypushback(int)} and a
   * match-all fallback rule) this method will only be called with things that
   * "Can't Possibly Happen".
   *
   * <p>If this method is called, something is seriously wrong (e.g. a JFlex bug producing a faulty
   * scanner etc.).
   *
   * <p>Usual syntax/scanner level error handling should be done in error fallback rules.
   *
   * @param errorCode the code of the error message to display.
   */
  private static void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    } catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  }


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * <p>They will be read again by then next call of the scanning method.
   *
   * @param number the number of characters to be read again. This number must not be greater than
   *     {@link #yylength()}.
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() throws java.io.IOException {
    if (!zzEOFDone) {
      zzEOFDone = true;
    
  yyclose();    }
  }




  /**
   * Resumes scanning until the next regular expression is matched, the end of input is encountered
   * or an I/O-Error occurs.
   *
   * @return the next token.
   * @exception java.io.IOException if any I/O-Error occurs.
   */
  @Override  public java_cup.runtime.Symbol next_token() throws java.io.IOException
  {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char[] zzBufferL = zzBuffer;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      yychar+= zzMarkedPosL-zzStartRead;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':  // fall through
        case '\u000C':  // fall through
        case '\u0085':  // fall through
        case '\u2028':  // fall through
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn += zzCharCount;
        }
      }

      if (zzR) {
        // peek one character ahead if it is
        // (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof)
            zzPeek = false;
          else
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;

      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {

          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMap(zzInput) ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
            zzDoEOF();
          { return new java_cup.runtime.Symbol(sym.EOF); }
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1:
            { erroresLexicos.add(new Excepcion(yytext()+"", "error lexico", Integer.toString(yyline+1), Integer.toString(yycolumn+1)));
            }
          // fall through
          case 60: break;
          case 2:
            { /* Espacios en blanco se ignoran */
            }
          // fall through
          case 61: break;
          case 3:
            { Rtokens.add(new token(yytext()+"", "Operacion Logica", Integer.toString(yyline+1), Integer.toString(yycolumn+1)));     return new Symbol(sym.NOTT, yycolumn, yyline, yytext());
            }
          // fall through
          case 62: break;
          case 4:
            { Rtokens.add(new token(yytext()+"", "Signo $", Integer.toString(yyline+1), Integer.toString(yycolumn+1)));     return new Symbol(sym.DOLAR, yycolumn, yyline, yytext());
            }
          // fall through
          case 63: break;
          case 5:
            { Rtokens.add(new token(yytext()+"", "Parentesis abierto", Integer.toString(yyline+1), Integer.toString(yycolumn+1)));         return new Symbol(sym.PARENA, yycolumn, yyline, yytext());
            }
          // fall through
          case 64: break;
          case 6:
            { Rtokens.add(new token(yytext()+"", "Parentensis cerrado", Integer.toString(yyline+1), Integer.toString(yycolumn+1)));        return new Symbol(sym.PARENC, yycolumn, yyline, yytext());
            }
          // fall through
          case 65: break;
          case 7:
            { Rtokens.add(new token(yytext()+"", "Operacion Aritmetica", Integer.toString(yyline+1), Integer.toString(yycolumn+1)));    return new Symbol(sym.MULTI, yycolumn, yyline, yytext());
            }
          // fall through
          case 66: break;
          case 8:
            { Rtokens.add(new token(yytext()+"", "Operacion Aritmetica", Integer.toString(yyline+1), Integer.toString(yycolumn+1)));   System.out.println("encontro suma");  return new Symbol(sym.MAS, yycolumn, yyline, yytext());
            }
          // fall through
          case 67: break;
          case 9:
            { Rtokens.add(new token(yytext()+"", "coma", Integer.toString(yyline+1), Integer.toString(yycolumn+1)));    return new Symbol(sym.COMA, yycolumn, yyline, yytext());
            }
          // fall through
          case 68: break;
          case 10:
            { Rtokens.add(new token(yytext()+"", "Operacion Aritmetica", Integer.toString(yyline+1), Integer.toString(yycolumn+1)));     return new Symbol(sym.MENOS, yycolumn, yyline, yytext());
            }
          // fall through
          case 69: break;
          case 11:
            { Rtokens.add(new token(yytext()+"", "Operacion Aritmetica", Integer.toString(yyline+1), Integer.toString(yycolumn+1)));      System.out.println("encontro division"); return new Symbol(sym.DIVISION, yycolumn, yyline, yytext());
            }
          // fall through
          case 70: break;
          case 12:
            { ;              Rtokens.add(new token(yytext()+"", "Numero" , Integer.toString(yyline+1), Integer.toString(yycolumn+1)));          return new Symbol(sym.NUMEROS, yycolumn, yyline, yytext());
            }
          // fall through
          case 71: break;
          case 13:
            { Rtokens.add(new token(yytext()+"", "Dos puntos", Integer.toString(yyline+1), Integer.toString(yycolumn+1)));     return new Symbol(sym.DPUNTOS, yycolumn, yyline, yytext());
            }
          // fall through
          case 72: break;
          case 14:
            { Rtokens.add(new token(yytext()+"", "Punto coma", Integer.toString(yyline+1), Integer.toString(yycolumn+1)));     return new Symbol(sym.PUNTOCOMA, yycolumn, yyline, yytext());
            }
          // fall through
          case 73: break;
          case 15:
            { Rtokens.add(new token(yytext()+"", "Operacion Racionale", Integer.toString(yyline+1), Integer.toString(yycolumn+1)));       return new Symbol(sym.MENOR, yycolumn, yyline, yytext());
            }
          // fall through
          case 74: break;
          case 16:
            { ;          Rtokens.add(new token(yytext()+"", "Signo =", Integer.toString(yyline+1), Integer.toString(yycolumn+1)));            return new Symbol(sym.IGUALSIMPLE, yycolumn, yyline, yytext());
            }
          // fall through
          case 75: break;
          case 17:
            { Rtokens.add(new token(yytext()+"", "Operacion Racionale", Integer.toString(yyline+1), Integer.toString(yycolumn+1)));     return new Symbol(sym.MAYOR, yycolumn, yyline, yytext());
            }
          // fall through
          case 76: break;
          case 18:
            { Rtokens.add(new token(yytext()+"", "Identificador", Integer.toString(yyline+1), Integer.toString(yycolumn+1)));          return new Symbol(sym.IDD, yycolumn, yyline, yytext());
            }
          // fall through
          case 77: break;
          case 19:
            { Rtokens.add(new token(yytext()+"", "Corchete abierto", Integer.toString(yyline+1), Integer.toString(yycolumn+1)));         return new Symbol(sym.CORA, yycolumn, yyline, yytext());
            }
          // fall through
          case 78: break;
          case 20:
            { Rtokens.add(new token(yytext()+"", "Corchete Cerrado", Integer.toString(yyline+1), Integer.toString(yycolumn+1)));       return new Symbol(sym.CORC, yycolumn, yyline, yytext());
            }
          // fall through
          case 79: break;
          case 21:
            { Rtokens.add(new token(yytext()+"", "Llave abierta", Integer.toString(yyline+1), Integer.toString(yycolumn+1)));      return new Symbol(sym.LLAVEA, yycolumn, yyline, yytext());
            }
          // fall through
          case 80: break;
          case 22:
            { Rtokens.add(new token(yytext()+"", "Llave Cierra", Integer.toString(yyline+1), Integer.toString(yycolumn+1)));     return new Symbol(sym.LLAVEC, yycolumn, yyline, yytext());
            }
          // fall through
          case 81: break;
          case 23:
            { Rtokens.add(new token(yytext()+"", "Operacion Racionale", Integer.toString(yyline+1), Integer.toString(yycolumn+1)));      return new Symbol(sym.DISTINTO, yycolumn, yyline, yytext());
            }
          // fall through
          case 82: break;
          case 24:
            { Rtokens.add(new token(yytext()+"", "Operacion Logica", Integer.toString(yyline+1), Integer.toString(yycolumn+1)));   return new Symbol(sym.ANDD, yycolumn, yyline, yytext());
            }
          // fall through
          case 83: break;
          case 25:
            { Rtokens.add(new token(yytext()+"", "Operacion Racionale", Integer.toString(yyline+1), Integer.toString(yycolumn+1)));        return new Symbol(sym.MENIGUAL, yycolumn, yyline, yytext());
            }
          // fall through
          case 84: break;
          case 26:
            { Rtokens.add(new token(yytext()+"", "Operacion Racionale", Integer.toString(yyline+1), Integer.toString(yycolumn+1)));      return new Symbol(sym.IGUAL, yycolumn, yyline, yytext());
            }
          // fall through
          case 85: break;
          case 27:
            { Rtokens.add(new token(yytext()+"", "Operacion Racionale", Integer.toString(yyline+1), Integer.toString(yycolumn+1)));        return new Symbol(sym.MAYIGUAL, yycolumn, yyline, yytext());
            }
          // fall through
          case 86: break;
          case 28:
            { Rtokens.add(new token(yytext()+"", "Sentencia Do", Integer.toString(yyline+1), Integer.toString(yycolumn+1)));  return new Symbol(sym.DOO,yycolumn, yyline, yytext());
            }
          // fall through
          case 87: break;
          case 29:
            { Rtokens.add(new token(yytext()+"", "Sentencia IF", Integer.toString(yyline+1), Integer.toString(yycolumn+1)));   return new Symbol(sym.IFF,yycolumn, yyline, yytext());
            }
          // fall through
          case 88: break;
          case 30:
            { Rtokens.add(new token(yytext()+"", "Operacion Logica", Integer.toString(yyline+1), Integer.toString(yycolumn+1)));    return new Symbol(sym.ORR, yycolumn, yyline, yytext());
            }
          // fall through
          case 89: break;
          case 31:
            { Rtokens.add(new token(yytext()+"", "Cadena", Integer.toString(yyline+1), Integer.toString(yycolumn+1)));             return new Symbol(sym.CADENA, yycolumn, yyline, yytext());
            }
          // fall through
          case 90: break;
          case 32:
            { Rtokens.add(new token(yytext()+"", "Comentario de una linea", Integer.toString(yyline+1), Integer.toString(yycolumn+1)));      System.out.println("se encontro un Comentario linea");
            }
          // fall through
          case 91: break;
          case 33:
            { Rtokens.add(new token(yytext()+"", "Sentencia For", Integer.toString(yyline+1), Integer.toString(yycolumn+1)));  return new Symbol(sym.FORR,yycolumn, yyline, yytext());
            }
          // fall through
          case 92: break;
          case 34:
            { Rtokens.add(new token(yytext()+"", "Tipos de Dato", Integer.toString(yyline+1), Integer.toString(yycolumn+1)));  return new Symbol(sym.INTT,yycolumn, yyline, yytext());
            }
          // fall through
          case 93: break;
          case 35:
            { Rtokens.add(new token(yytext()+"", "Comentario multilinea", Integer.toString(yyline+1), Integer.toString(yycolumn+1)));      System.out.println("se encontro un comentarioLineas");
            }
          // fall through
          case 94: break;
          case 36:
            { Rtokens.add(new token(yytext()+"", "Tipos de Dato", Integer.toString(yyline+1), Integer.toString(yycolumn+1)));  return new Symbol(sym.BOOLL,yycolumn, yyline, yytext());
            }
          // fall through
          case 95: break;
          case 37:
            { Rtokens.add(new token(yytext()+"", "Sentencia Case", Integer.toString(yyline+1), Integer.toString(yycolumn+1)));  return new Symbol(sym.CASEE,yycolumn, yyline, yytext());
            }
          // fall through
          case 96: break;
          case 38:
            { Rtokens.add(new token(yytext()+"", "Tipos de Dato", Integer.toString(yyline+1), Integer.toString(yycolumn+1)));  return new Symbol(sym.CHARR,yycolumn, yyline, yytext());
            }
          // fall through
          case 97: break;
          case 39:
            { Rtokens.add(new token(yytext()+"", "Palabra reservada Eje X", Integer.toString(yyline+1), Integer.toString(yycolumn+1)));  return new Symbol(sym.EJEX,yycolumn, yyline, yytext());
            }
          // fall through
          case 98: break;
          case 40:
            { Rtokens.add(new token(yytext()+"", "Setencia Else", Integer.toString(yyline+1), Integer.toString(yycolumn+1)));  return new Symbol(sym.ELSEE,yycolumn, yyline, yytext());
            }
          // fall through
          case 99: break;
          case 41:
            { Rtokens.add(new token(yytext()+"", "Valor Booleano", Integer.toString(yyline+1), Integer.toString(yycolumn+1)));  return new Symbol(sym.VERDAD,yycolumn, yyline, yytext());
            }
          // fall through
          case 100: break;
          case 42:
            { Rtokens.add(new token(yytext()+"", "Break", Integer.toString(yyline+1), Integer.toString(yycolumn+1)));  return new Symbol(sym.BREAKK,yycolumn, yyline, yytext());
            }
          // fall through
          case 101: break;
          case 43:
            { Rtokens.add(new token(yytext()+"", "Valor Booleano", Integer.toString(yyline+1), Integer.toString(yycolumn+1)));  return new Symbol(sym.FALSO,yycolumn, yyline, yytext());
            }
          // fall through
          case 102: break;
          case 44:
            { Rtokens.add(new token(yytext()+"", "Sentencia While", Integer.toString(yyline+1), Integer.toString(yycolumn+1)));return new Symbol(sym.WHILEE,yycolumn, yyline, yytext());
            }
          // fall through
          case 103: break;
          case 45:
            { Rtokens.add(new token(yytext()+"", "Tipos de Dato", Integer.toString(yyline+1), Integer.toString(yycolumn+1)));  return new Symbol(sym.DOUBLEE,yycolumn, yyline, yytext());
            }
          // fall through
          case 104: break;
          case 46:
            { Rtokens.add(new token(yytext()+"", "Tipos de Dato", Integer.toString(yyline+1), Integer.toString(yycolumn+1)));  return new Symbol(sym.STRINGG,yycolumn, yyline, yytext());
            }
          // fall through
          case 105: break;
          case 47:
            { Rtokens.add(new token(yytext()+"", "Sentencia Switch", Integer.toString(yyline+1), Integer.toString(yycolumn+1)));  return new Symbol(sym.SWITCHH,yycolumn, yyline, yytext());
            }
          // fall through
          case 106: break;
          case 48:
            { Rtokens.add(new token(yytext()+"", "Palabra reservada Titulo", Integer.toString(yyline+1), Integer.toString(yycolumn+1)));   return new Symbol(sym.TITULO,yycolumn, yyline, yytext());
            }
          // fall through
          case 107: break;
          case 49:
            { Rtokens.add(new token(yytext()+"", "Default", Integer.toString(yyline+1), Integer.toString(yycolumn+1)));  return new Symbol(sym.DEFAULTT,yycolumn, yyline, yytext());
            }
          // fall through
          case 108: break;
          case 50:
            { Rtokens.add(new token(yytext()+"", "Sentencia Else If", Integer.toString(yyline+1), Integer.toString(yycolumn+1)));  return new Symbol(sym.ELSEIF,yycolumn, yyline, yytext());
            }
          // fall through
          case 109: break;
          case 51:
            { Rtokens.add(new token(yytext()+"", "Palabra reservada Titulos X", Integer.toString(yyline+1), Integer.toString(yycolumn+1)));  return new Symbol(sym.TITULOX,yycolumn, yyline, yytext());
            }
          // fall through
          case 110: break;
          case 52:
            { Rtokens.add(new token(yytext()+"", "Palabra reservada Titulo Y", Integer.toString(yyline+1), Integer.toString(yycolumn+1)));  return new Symbol(sym.TITULOY,yycolumn, yyline, yytext());
            }
          // fall through
          case 111: break;
          case 53:
            { Rtokens.add(new token(yytext()+"", "Palabra reservada Valores", Integer.toString(yyline+1), Integer.toString(yycolumn+1)));   return new Symbol(sym.VAL,yycolumn, yyline, yytext());
            }
          // fall through
          case 112: break;
          case 54:
            { Rtokens.add(new token(yytext()+"", "<NewValor>", Integer.toString(yyline+1), Integer.toString(yycolumn+1)));           return new Symbol(sym.NVALOR,yycolumn, yyline, yytext());
            }
          // fall through
          case 113: break;
          case 55:
            { Rtokens.add(new token(yytext()+"", "Declaración del main", Integer.toString(yyline+1), Integer.toString(yycolumn+1)));  return new Symbol(sym.VOIDD,yycolumn, yyline, yytext());
            }
          // fall through
          case 114: break;
          case 56:
            { Rtokens.add(new token(yytext()+"", "Sentencia Imprimir", Integer.toString(yyline+1), Integer.toString(yycolumn+1)));  return new Symbol(sym.PRINT,yycolumn, yyline, yytext());
            }
          // fall through
          case 115: break;
          case 57:
            { Rtokens.add(new token(yytext()+"", "Declaración Gráfica de Pie", Integer.toString(yyline+1), Integer.toString(yycolumn+1)));   return new Symbol(sym.PIE,yycolumn, yyline, yytext());
            }
          // fall through
          case 116: break;
          case 58:
            { Rtokens.add(new token(yytext()+"", "Declaración Gráfica de Barras", Integer.toString(yyline+1), Integer.toString(yycolumn+1)));  return new Symbol(sym.BARRAS,yycolumn, yyline, yytext());
            }
          // fall through
          case 117: break;
          case 59:
            { Rtokens.add(new token(yytext()+"", "Declaración Variables Globales", Integer.toString(yyline+1), Integer.toString(yycolumn+1)));   return new Symbol(sym.GLOBAL,yycolumn, yyline, yytext());
            }
          // fall through
          case 118: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }


}
