
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package Analizador;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int PARENC = 46;
  public static final int VAL = 55;
  public static final int PARENA = 45;
  public static final int DISTINTO = 32;
  public static final int CHARR = 21;
  public static final int WHILEE = 7;
  public static final int BREAKK = 14;
  public static final int STRINGG = 23;
  public static final int NUMEROS = 52;
  public static final int PIE = 36;
  public static final int PORCENTAJE = 11;
  public static final int PUNTOCOMA = 48;
  public static final int ORR = 41;
  public static final int TITULOY = 57;
  public static final int TITULOX = 56;
  public static final int EJEX = 54;
  public static final int ELSEIF = 26;
  public static final int IGUAL = 31;
  public static final int BARRAS = 35;
  public static final int VERDAD = 2;
  public static final int TITULO = 53;
  public static final int MAYIGUAL = 29;
  public static final int ELSEE = 27;
  public static final int CASEE = 13;
  public static final int EOF = 0;
  public static final int DOO = 8;
  public static final int VOIDD = 24;
  public static final int error = 1;
  public static final int COMA = 49;
  public static final int CADENA = 50;
  public static final int MENOS = 16;
  public static final int NOTT = 42;
  public static final int MENOR = 28;
  public static final int SWITCHH = 12;
  public static final int GLOBAL = 34;
  public static final int BOOLL = 22;
  public static final int DEFAULTT = 15;
  public static final int IDD = 51;
  public static final int INTT = 4;
  public static final int MAYOR = 19;
  public static final int DOUBLEE = 5;
  public static final int ANDD = 33;
  public static final int MENIGUAL = 30;
  public static final int IGUALSIMPLE = 20;
  public static final int FALSO = 3;
  public static final int DPUNTOS = 47;
  public static final int MULTI = 18;
  public static final int CORC = 40;
  public static final int CORA = 39;
  public static final int DIVISION = 17;
  public static final int LLAVEC = 44;
  public static final int DOLAR = 37;
  public static final int LLAVEA = 43;
  public static final int NVALOR = 38;
  public static final int IFF = 25;
  public static final int FORR = 6;
  public static final int PRINT = 9;
  public static final int MAS = 10;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "VERDAD",
  "FALSO",
  "INTT",
  "DOUBLEE",
  "FORR",
  "WHILEE",
  "DOO",
  "PRINT",
  "MAS",
  "PORCENTAJE",
  "SWITCHH",
  "CASEE",
  "BREAKK",
  "DEFAULTT",
  "MENOS",
  "DIVISION",
  "MULTI",
  "MAYOR",
  "IGUALSIMPLE",
  "CHARR",
  "BOOLL",
  "STRINGG",
  "VOIDD",
  "IFF",
  "ELSEIF",
  "ELSEE",
  "MENOR",
  "MAYIGUAL",
  "MENIGUAL",
  "IGUAL",
  "DISTINTO",
  "ANDD",
  "GLOBAL",
  "BARRAS",
  "PIE",
  "DOLAR",
  "NVALOR",
  "CORA",
  "CORC",
  "ORR",
  "NOTT",
  "LLAVEA",
  "LLAVEC",
  "PARENA",
  "PARENC",
  "DPUNTOS",
  "PUNTOCOMA",
  "COMA",
  "CADENA",
  "IDD",
  "NUMEROS",
  "TITULO",
  "EJEX",
  "VAL",
  "TITULOX",
  "TITULOY"
  };
}

